name: Java CI

on:
  release:
    types: [created]
  push:
    branches:
      - main
      - 'feature/*'
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest
