name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

    # Ajoutez des étapes supplémentaires selon vos besoins, par exemple :
    # - name: Run Tests
    #   run: mvn test

    # - name: Deploy to production
    #   run: ./deploy.sh
    #   env:
    #     API_KEY: ${{ secrets.PRODUCTION_API_KEY }}
